### ISSUE TITLE
Modifying process when a voucher vote "no" for an application

### ISSUE THREAD

**Issue by hugosolar** [creativecommons/commoners#370]
From "CC Rejected members policy"

"An email to the applicant will be sent explaining that the application has been rejected by one of the vouchers hence the Membership Committee will review the case following the process detailed below. No details are provided regarding who voted against the application or requested additional information"

## To-do
- Sent an email to the applicant explaining the rejection and next steps
- The application should be reviewed by MC
    - Change user status / pause application
    - Color highlight in the list of applications to be reviewed by Membership Committee
- If MC approves the application:
   - Send email to applicant asking to choose another voucher
- If MC denies the application:
   - Send an email to the applicant. Provide information about how they may appeal the decision

**Comment by hugosolar** [comment]
Status
- [x] New email field in Settings > CCGN emails: email notifies the applicant that the application will be reviewed by the MC
- [x] New user status defined 'to-be-reviewed' 
- [x] Include users with new status in "Applications for approval" screen (Global Network > Application approval)
- [x] Highlight users with the new status in "Applications for approval" screen
- [ ] Add new Gform for MC review (yes/no/reason)
- [ ] Add submit handler for MC review Form
- [ ] New email field in settings > CCGN emails: Email notifies the applicant when MC reviews the application and send to the applicant the MC resolution
